import type { Metadata } from "next"
import "./globals.css"

import { instrumentSans, instrumentSerif } from "@/app/fonts"
import { cn } from "@/lib/utils"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="pt-BR"
      className={cn(instrumentSans.variable, instrumentSerif.variable)}
    >
      <body>{children}</body>
    </html>
  )
}
